name: lms_mobile
description: "TDTU LMS - Ta'lim boshqaruv tizimi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  fl_chart: ^0.69.0
  cached_network_image: ^3.4.0
  pull_to_refresh_flutter3: ^2.0.2
  flutter_svg: ^2.0.0
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
